Enhancement |  Refactor common.tfvars account vars
binbashar/le-tf-infra-aws pull request #402
Opened 2022-07-08 01:14 UTC by eze-godoy

## What?
* Remove old variable blocks. _Example:_  
```
variable "xxxx_account_id" {
  type        = string
  description = "Account: Xxxx"
}
```

* Update variables in all layers. _Example:_   
```
# Before:
  trusted_role_arns = [
    "arn:aws:iam::${var.root_account_id}:root"
  ]

# Now:
  trusted_role_arns = [
    "arn:aws:iam::${var.accounts.root.id}:root"
  ]
```

* Update `common.tfvars.example`

## Why?
Improve code readability and flexibility

2022-07-08 15:10 UTC, exequielrafaela requested changes
@eze-godoy Let's take this opportunity to also update the ref arch with the current naming convention for AWS Organizations from `root` to `management` account in [the map definition](https://github.com/binbashar/le-tf-infra-aws/blob/85c5829d2c826dc9000a1943079507319cf037d5/config/common.tfvars.example#L23). Since this is only a variable name it won't affect any deployed resources.  

**From** 
- `var.accounts.root.id`

**To** 
- `var.accounts.management.id`

**CONSIDERATION:** Were you able to smoke test several Ref Arch layers with successful results?

2022-07-11 15:21 UTC, eze-godoy commented
Hi @exequielrafaela. I made the requested change. I also performed some smoke tests in modules that use these variables without errors 🚀 .

2022-07-11 21:53 UTC, exequielrafaela approved these changes

2022-07-11 21:53 UTC, exequielrafaela commented
> Hi @exequielrafaela. I made the requested change. I also performed some smoke tests in modules that use these variables without errors 🚀 .

@eze-godoy that's great! PR approved 🚀

2022-07-12 13:38 UTC, merged