Feature | Implement external-secrets for Apps-DevStg K8s-EKS cluster
binbashar/le-tf-infra-aws pull request #416
Opened 2022-07-29 13:23 UTC by angelofenoglio

## What?
* Add the Identities needed by `external-secrets`
* Bump `iam-assumable-role-with-oidc` modules version
* Fix reference to the domain's certificate arn
* Fix backend state bucket key for VPN server
* Implement `external-secrets` component in cluster

## Why?
* To be able to consume secrets stored in Secrets Manager and Parameter Store form within a cluster node.

2022-07-29 13:56 UTC, fgauchat-binbash submitted a review, later dismissed
looks good! thanks @angelofenoglio

2022-07-29 14:57 UTC, exequielrafaela requested changes
@angelofenoglio great collab here! Let's run the terraform fmt (`leverage terraform format`) to grant tf canonical fmt. Thanks!

2022-08-19 21:17 UTC, diego-ojeda-binbash approved these changes

2022-09-26 14:26 UTC, exequielrafaela approved these changes

2022-09-30 14:50 UTC, exequielrafaela approved these changes

2022-10-06 15:03 UTC, diego-ojeda-binbash approved these changes

2022-10-06 15:06 UTC, merged