477 | Enable ALB access logs for EKS clusters
binbashar/le-tf-infra-aws pull request #484
Opened 2023-03-12 17:20 UTC by Franr

## What?
We are adding a variable to create a bucket and enable access logs on the EKS ALB.

## Why?
For security/traceability.

## References
`closes #477`

2023-03-28 14:41 UTC, exequielrafaela commented
@Franr Cisco there's anything else pending before we can change this PR from draft? Let's us know and we could review it when needed.

2023-03-28 15:45 UTC, Franr commented
> @Franr Cisco there's anything else pending before we can change this PR from draft? Let's us know and we could review it when needed.

yes, I was not able to bring up the cluster to be able to test it... there were some errors and I desisted.
If the is another cluster up (like demoapps), I could try there!

2023-03-29 19:49 UTC, Franr commented
@exequielrafaela alright Exe, I was finally able to test it! Moving the PR into ready to review.

2023-03-29 21:12 UTC, exequielrafaela commented
@Franr small one related to CI test for terraform canonical format => https://app.circleci.com/pipelines/github/binbashar/le-tf-infra-aws/3095/workflows/b22009a1-7f14-47b9-b243-b51deb4be59a/jobs/3876 easily fixed with `leverage terraform format` cmd 💪🏼

2023-03-30 14:32 UTC, diego-ojeda-binbash requested changes

2023-03-30 14:32 UTC, diego-ojeda-binbash commented on apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/networking-ingress.tf
> +      "alb.ingress.kubernetes.io/load-balancer-attributes" = "access_logs.s3.enabled=${var.enable_eks_alb_logging},access_logs.s3.bucket=${var.project}-${var.environment}-alb-logs,access_logs.s3.pref
I think this `access_logs.s3.prefix=eks-cluster-demoapps-ingress` should also be defined through a variable.

2023-03-30 14:32 UTC, diego-ojeda-binbash commented on apps-devstg/us-east-1/k8s-eks/cluster/config.tf
> +  required_version = "~> 1.2.7"
```suggestion
  required_version = "~> 1.2"
```

2023-03-30 14:32 UTC, diego-ojeda-binbash commented on apps-devstg/us-east-1/k8s-eks/k8s-components/networking-ingress.tf
> +      "alb.ingress.kubernetes.io/load-balancer-attributes" = "access_logs.s3.enabled=${var.enable_eks_alb_logging},access_logs.s3.bucket=${var.project}-${var.environment}-alb-logs,access_logs.s3.pref
I think this `access_logs.s3.prefix=eks-cluster-ingress` should also be defined through a variable.

2023-03-30 14:32 UTC, diego-ojeda-binbash commented on apps-devstg/us-east-1/security-audit/logs.tf
> +  source = "github.com/binbashar/terraform-aws-s3-bucket.git?ref=v3.7.0"
Could you make this module easy to enable/disable through a variable? I would like this to be optional. 🙏

2023-03-30 18:47 UTC, Franr commented on apps-devstg/us-east-1/k8s-eks/identities/ids_external_secrets.tf
> +        "${data.terraform_remote_state.shared-keys.outputs.aws_kms_key_arn}"
a bug I found while creating the identities of the cluster, the state is called `shared-keys`, not `shared`

2023-03-30 18:52 UTC, diego-ojeda-binbash approved these changes

2023-03-30 19:10 UTC, diego-ojeda-binbash approved these changes

2023-03-30 19:11 UTC, merged