Issue 500 feature add reference secret manager implementation demoapps
binbashar/le-tf-infra-aws pull request #503
Opened 2023-04-20 18:31 UTC by marianod92

## What?
*

## Why?
*

## References
*

2023-04-24 09:57 UTC, Franr reviewed
left a few comments!

2023-04-24 09:57 UTC, Franr commented on apps-devstg/us-east-1/k8s-eks-demoapps/k8s-components/security.tf
>  # These resources below (cluster_secrets_manager and cluster_parameter_store) need to be commented out and applied in a second step
I guess this comment doesn't apply anymore?

2023-04-24 09:57 UTC, Franr commented on apps-devstg/us-east-1/k8s-eks-demoapps/identities/config.tf
> +}
```suggestion
}

```

2023-04-24 09:57 UTC, Franr commented on apps-devstg/us-east-1/k8s-eks-demoapps/secrets/config.tf
> +# Note: Commented out while database is not deployed
unnecessary?

2023-04-24 09:57 UTC, Franr commented on apps-devstg/us-east-1/k8s-eks-demoapps/identities/config.tf
> +    key     = "${var.environment}/security-keys/terraform.tfstate"
isn't this the same state than `apps-devsgt-keys`? shouldn't it be `security/.....` instead?

2023-04-24 15:11 UTC, diego-ojeda-binbash requested changes

2023-04-24 15:11 UTC, diego-ojeda-binbash commented on apps-devstg/us-east-1/k8s-eks-demoapps/identities/config.tf
> +data "terraform_remote_state" "apps-devsgt-keys" {
Small typo: `devsgt`

2023-04-24 15:11 UTC, diego-ojeda-binbash commented on apps-devstg/us-east-1/k8s-eks-demoapps/identities/config.tf
> +data "terraform_remote_state" "apps-devsgt-keys" {
Also, if the data points to a resource in the same account we typically don't include the account name in the data resource name (e.g. check the data block right above that is named "cluster"). So in this case, the data could just be named "keys".

2023-04-24 15:11 UTC, diego-ojeda-binbash commented on apps-devstg/us-east-1/k8s-eks-demoapps/identities/config.tf
> +    key     = "${var.environment}/security-keys/terraform.tfstate"
This ☝️

2023-04-27 17:47 UTC, Franr approved these changes

2023-04-27 20:24 UTC, marianod92 commented
- Test after modifications

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/35702375/234981742-55d16c74-2613-4a21-b555-3c6acaa39868.png">
<img width="758" alt="image" src="https://user-images.githubusercontent.com/35702375/234981840-0a3712cd-a933-4c31-aa39-20909ce68313.png">
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/35702375/234982363-152387bb-dcf9-46e1-bb82-fbb75913fb8b.png">

2023-04-28 11:18 UTC, Franr approved these changes

2023-04-28 13:31 UTC, diego-ojeda-binbash approved these changes

2023-04-28 14:09 UTC, merged