Feature/genai poc
binbashar/le-tf-infra-aws pull request #612
Opened 2024-08-22 19:43 UTC by martingaleano

## What?
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## Why?
* Provide the justifications for the changes (e.g. business case).
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## References
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow).
* Use `closes #123`, if this PR closes a GitHub issue `#123`

2024-08-25 23:13 UTC, exequielrafaela approved these changes

2024-08-25 23:15 UTC, exequielrafaela requested changes
@martingaleano Tincho let's please use binbash.co instead of binbash.com.ar domain. Thanks!

2024-08-26 17:10 UTC, martingaleano commented
> @martingaleano Tincho let's please use binbash.co instead of binbash.com.ar domain. Thanks!

Thanks @exequielrafaela . I've just moved the domain to binbash.co

2024-08-26 17:51 UTC, exequielrafaela approved these changes

2024-08-27 13:59 UTC, diego-ojeda-binbash commented on data-science/us-east-1/genai-llm-rag-bedrock-poc/locals.tf
> +      memory = 2048
@martingaleano does this container require this much resources?

2024-08-27 18:17 UTC, martingaleano commented on data-science/us-east-1/genai-llm-rag-bedrock-poc/locals.tf
> +      memory = 2048
@diego-ojeda-binbash  No, it doesn't. I've just updated the PR and replaced those values with cpu = 512 and memory = 1024. I think  these values fit much better.

2024-08-27 21:27 UTC, diego-ojeda-binbash approved these changes

2024-09-03 18:21 UTC, merged